### ISSUE TITLE
Apply headers of batch requests to sub-requests

### ISSUE THREAD

**Issue by petronellius** [Tornhoof/HttpBatchHandler#14]
It'd be nice feature if e.g. Authorization header is need to be provided only for batch request and it is then automatically apply for every sub-request. Same approach uses [google batch api](https://developers.google.com/classroom/guides/batch).

As a workaround BatchRequestPreparationContext could contain batch request context. Then it'll be possible to update RequestFeature in BatchRequestPreparationAsync event.

**Comment by Tornhoof** [comment]
To easily solve that is by creating your own state object, assigning it in BatchStartAsync and using that do pass whatever information you need from the original request down to each event.
See:
https://github.com/Tornhoof/HttpBatchHandler/blob/0eab053dba14f3212ff85b7f067557b9898b07d9/src/HttpBatchHandler/BatchMiddleware.cs#L93-L98

**Comment by petronellius** [comment]
Sounds great. I will do it this way. It is really good idea to allow programmers to change behaviour of your middleware through event hooks :thumbsup:
