### ISSUE TITLE
Exception messages are written in Response stream

### ISSUE THREAD

**Issue by vishiitr** [Tornhoof/HttpBatchHandler#19]
If any exception is raised in any of the batch, then it is being silently absorbed instead of returning 500 or something else that for that particular request.

**Comment by Tornhoof** [comment]
That's your job. Handle the BatchRequestExecutedAsync Event and decide yourself on what you want to do with that request. This is necessary, so you can decide if you want to continue with other requests or just abort everything.
Take a look at
https://github.com/Tornhoof/HttpBatchHandler/blob/11a36af2f712646b2a257d9177f6e997c07a0984/src/HttpBatchHandler/BatchMiddleware.cs#L126-L135

**Comment by PavelDanov** [comment]
@Tornhoof I just started looking at your library, how would I go about to handle that event? Let's say I've overridden BatchStartAsync and an error happens inside.

**Comment by Tornhoof** [comment]
It is highly unlikely that an Error happens in BatchStartAsync, those errors are probably not recoverable anyway, the errors you want to handle are in BatchRequestExecutedAsync.
Then the steps are:
1. Implement your own type derived from BatchMiddlewareEvents (you can also handle individual events, but if you want a more complex scenario, a custom type is the easiest way)
2. Override BatchStartAsync and set context.State to a custom class (BatchState in the example below) in which you track data
3. Overrie BatchRequestExecutedAsync and do something like
```csharp
        public override Task BatchRequestExecutedAsync(BatchRequestExecutedContext context, CancellationToken cancellationToken = default)
        {
            var state = (BatchState) context.State;
            var response = context.Response;
            if (!response.IsSuccessStatusCode())
            {
                context.Abort = true; // aborts further procesing
               state.StatusCode = context.Response.StatusCode; 
            }
            return Task.CompletedTask;
        }
```
4. override BatchEndAsync
```csharp
        public override async Task BatchEndAsync(BatchEndContext context, CancellationToken cancellationToken = default)
        {
            var state = (BatchState) context.State;
                if (context.IsAborted)
                {
                    context.Response.StatusCode = state.StatusCode;
                }
        }
```

The example steps above basically, abort the batch processing if an individual request failed and set the status code of the batch response to the status code collected in the individual request.

BatchState looks  like:
```csharp
public class BatchState
{
            public int StatusCode { get; set; }
}
```

With a custom batchstate object you can track the information through each of the individual steps and make sure you don't forget any error inbetween.

**Comment by PavelDanov** [comment]
Thanks @Tornhoof ! That makes sense and it's working 👍

**Comment by maxiptah** [comment]
I want the exception to be actually present in the Response, e.g.:
```
--b1ced9fa-2faa-42a1-bbad-3d1344b13a41
Content-Type: application/http; msgtype=response

1.1 403 not ok

{ "Error": "User is not granted write policy." }
--b1ced9fa-2faa-42a1-bbad-3d1344b13a41--

```
How would I achieve that? I've subscribed to OnBatchRequestExecutedAsync and I can read out my exception BatchRequestExecutedContext.Exception, but how do I attach it to the Response stream? Would not I need an instance of the MultipartWriter from the BatchMiddleware for this?

I've tried the following:
```
private async Task BatchExecuted(BatchRequestExecutedContext ctx, CancellationToken arg2)
{
var context = ctx.State as HttpContext;
using var writer = new MultipartWriter("batch", Guid.NewGuid().ToString());
using var t =  new HttpApplicationMultipart("1.1", (int)statusCode, "not ok", error, new HeaderDictionary());
writer.Add(t);
await writer.CopyToAsync(context.Response.Body, arg2);
}
```
This kind of works if all requests in batch are faulty. However if at least on of them is not, it's not present in the Response, so I guess I overwrite the whole Response and data from the BatchMiddleware is not written.

**Comment by Tornhoof** [comment]
This is not job of this middleware, if you want to handle exceptions for individual requests (this includes writing custom error messages for a specific request), you need to use the exception handling in asp.net core. That one is called long before the batch handler.

**Comment by maxiptah** [comment]
Thank you for your fast response!
I do have asp.net core exception handling [set up:](UseExceptionHandler)
```
app.UseExceptionHandler(errorApp =>
            {
                errorApp.Run(async context =>
                {
                      // do whatever needed with custom exception types
context.Response.StatusCode = (int)statusCode;
                    context.Response.ContentType = "application/json";
                    await context.Response.WriteAsync(JsonConvert.SerializeObject(error, new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver(), }));
}
}
```
This works fine for normal requests. However this only works if exception is raised and thrown, and in case of batch this exception is handled by the middleware here:
```
catch (Exception ex)
                                {
                                    state.Abort(ex);
                                    executedContext.Exception = ex;
                                }
```
So I'm never hittin my exception handler. Am I missing something?

**Comment by Tornhoof** [comment]
The order you registered the handlers is probably wrong. Try swapping AddExceptionHandler and AddBatchHandler.

**Comment by maxiptah** [comment]
That was it! Thank you very much! Now everything is working.

One last question (not exactly for this thread, but close): is the order of the responses in the batch garanteed? I.e. if I send 50 requests in one batch and the 5th one produced an exception, will it be on the 5th position in the response? I'm thinking about how can client actually match responses to the requests.

**Comment by Tornhoof** [comment]
The order is the same. Otherwise you can add some kind of custom tracking information via ``BatchRequestExecutedAsync`` or similar.
