### ISSUE TITLE
Seems to cause null reference exception when used with the latest (3.0.0-preview8.19405.7) .Net Core 3.0 preview

### ISSUE THREAD

**Issue by ibasin** [Tornhoof/HttpBatchHandler#20]
I am trying to use your source code to make a batch processor for .NEt Core 3.0 Preview. It appears to cause a null reference exception in one of the downstream middleware components (app.UseEndpoints).

This is really easy to reproduce. Just make your your dll to be .NEt 3.0 and change your Startup.cs to this (to comply with the new routing scheme):

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (_pathBase != "/")
            {
                app.UsePathBase(_pathBase);
            }

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseBatchMiddleware();

            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
            });
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddRazorPages();        
        }

When using .Net Core 3.0, await _next.Invoke(state.Context).ConfigureAwait(false); line in InvokeBatchAsync method of BatchMiddleware causes app.UseEndpoints middleware to generate a null exception. 

 Please help.

**Comment by ibasin** [comment]
By the way, thank you for publishing it. It is super useful and works great for .Net Core 2.2.

**Comment by Tornhoof** [comment]
There is no Support for 3.0 yet, they changed too much inbetween previews.  You can take a look at the tes branch, that's the current inprogress Version for 3.0

**Comment by ibasin** [comment]
It appears that setting up the Response.Body (like this: state.Context.Response.Body = new MemoryStream(); ) right before the _next.Invoke call fixes the problem. 

Not sure if it fixes it for all scenarios though...

**Comment by ibasin** [comment]
I understand that there is no support for 3.0 but could you characterize the condition of "tes" branch: is it (a) working now for 3.0, just not stable yet or is it (b) work in progress (not fully functional yet)?

Thank you in advance!

**Comment by Tornhoof** [comment]
Well the Tests pass, haven't looked any further than  that and I wouldn't bet that it will keep working in the next preview.

**Comment by ibasin** [comment]
Thank you!!!
