### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by srikrsna** [Tornhoof/HttpBatchHandler#3]
Can this be published to in Nuget? If not does this need any more development work. If yes I am happy to contribute to the project.

Thanks.

**Comment by Tornhoof** [comment]
I refrained from publishing it on Nuget, because I intended it to folded into one of the middleware collections (BasicMiddlewares, aspnetcontrib etc.), but I'll see that I'll get it ony nuget as apparently the need for this middleware is not that great as previously expected.

**Comment by srikrsna** [comment]
Thank You. Really appreciate the work.

**Comment by Tornhoof** [comment]
The nuget package for 0.3 is published here: https://www.nuget.org/packages/HttpBatchHandler
It includes a few naming fixes (you might need changes in your code for them) from #4
