### ISSUE TITLE
Request method 'OPTIONS' not supported

### ISSUE THREAD

**Issue by Yauheniii** [Tornhoof/HttpBatchHandler#9]
I have a case with CORS request. 
'OPTIONS' sent before 'POST' in the browser for these requests but I get an error "Invalid Content-Type." because OPTIONS request has not contains multipart content-type header. This validation implemented [here](https://github.com/Tornhoof/HttpBatchHandler/blob/master/src/HttpBatchHandler/BatchMiddleware.cs):

`if (!httpContext.Request.IsMultiPartBatchRequest())`
`{`
`	httpContext.Response.StatusCode = StatusCodes.Status400BadRequest;`
`	await httpContext.Response.WriteAsync("Invalid Content-Type.").ConfigureAwait(false);`
`	return;`
`}`

I think in this case need to skip processing a batch logic and return to main handler.
Like this:
`if (!httpContext.Request.Path.Equals(_options.Match) || "OPTIONS" == httpContext.Request.Method)`
`{`
               ` return _next.Invoke(httpContext);`
`}`
or something else.

**Comment by Tornhoof** [comment]
Make sure your CORS middleware is setup correctly before the batch middleware, the CORS middleware should handle the CORS request and not call the batch middleware.

**Comment by Yauheniii** [comment]
Yep, CORS working correctly for all requests except batch.
I'm using Microsoft.AspNetCore.Cors library.

`app.UseCors(p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod());`
`app.UseBatchMiddleware();`
` app.UseMvc();`

As I can see batch middleware always called before CORS middleware.
Do you think it may be incorrect CORS implementation?

**Comment by Tornhoof** [comment]
The order looks correct, the middleware https://github.com/aspnet/CORS/blob/737dfad13318e9d39664d761cc3eaff7ee4c83b8/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsMiddleware.cs#L102 should get the request then if the AccessControlRequestMethod Header is set.

**Comment by Yauheniii** [comment]
Right, I updated AspNetCore from 2.0.5 to 2.0.6 and issue has been resolved.
Thanks!
